apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: devops-portfolio
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: laly9999/order-service:2
          ports:
            - name: http
              containerPort: 8082
          env:
            - name: DB_URI
              value: mongodb://mongo:27017/orderdb
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:8081
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: devops-portfolio
  labels:
    app: order-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082







#################################







# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: order-service
#   namespace: devops-portfolio
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: order-service
#   template:
#     metadata:
#       labels:
#         app: order-service
#     spec:
#       containers:
#         - name: order-service
#           image: laly9999/order-service:1
#           ports:
#             - containerPort: 8082
#           env:
#             - name: DB_URI
#               value: mongodb://mongo:27017/orderdb
#             - name: PRODUCT_SERVICE_URL
#               value: http://product-service:8081
#           resources:
#             requests:
#               cpu: "100m"
#               memory: "128Mi"
#             limits:
#               cpu: "200m"
#               memory: "256Mi"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: order-service
#   namespace: devops-portfolio
# spec:
#   selector:
#     app: order-service
#   ports:
#     - port: 8082
#       targetPort: 8082




######################################




# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: order-service-monitor
#   namespace: monitoring
#   labels:
#     release: prometheus-stack         # ðŸ‘ˆ match your kube-prometheus-stack release label
# spec:
#   selector:
#     matchLabels:
#       app: order-service              # ðŸ‘ˆ matches Service label
#   namespaceSelector:
#     matchNames:
#       - devops-portfolio              # ðŸ‘ˆ where the Service lives
#   endpoints:
#     - port: http                      # ðŸ‘ˆ matches 'ports.name' in the Service
#       path: /metrics
#       interval: 15s
#       scrapeTimeout: 10s








# Important: the release label

# In many setups with kube-prometheus-stack, Prometheus only picks ServiceMonitor objects that have a label like:

# release: prometheus or

# release: kube-prometheus-stack

# You must use the same value your Helm release uses.

# You can check it with:

# kubectl get servicemonitors -A