apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: devops-portfolio
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: laly9999/product-service:2
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: DB_URI
              value: mongodb://mongo:27017/productdb
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: devops-portfolio
  labels:
    app: product-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: product-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081




############################################

# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: product-service-monitor
#   namespace: monitoring
#   labels:
#     release: prometheus-stack        # ðŸ‘ˆ change to match your Helm release label
# spec:
#   selector:
#     matchLabels:
#       app: product-service           # ðŸ‘ˆ matches the Service label
#   namespaceSelector:
#     matchNames:
#       - devops-portfolio             # ðŸ‘ˆ where product-service runs
#   endpoints:
#     - port: http                     # ðŸ‘ˆ matches Service port name
#       path: /metrics
#       interval: 15s
#       scrapeTimeout: 10s




######################################





# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: product-service
#   namespace: devops-portfolio
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: product-service
#   template:
#     metadata:
#       labels:
#         app: product-service
#     spec:
#       containers:
#         - name: product-service
#           image: laly9999/product-service:1
#           ports:
#             - containerPort: 8081
#           env:
#             - name: DB_URI
#               value: mongodb://mongo:27017/productdb
#           resources:
#             requests:
#               cpu: "100m"
#               memory: "128Mi"
#             limits:
#               cpu: "200m"
#               memory: "256Mi"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: product-service
#   namespace: devops-portfolio
# spec:
#   selector:
#     app: product-service
#   ports:
#     - port: 8081
#       targetPort: 8081






